### ISSUE TITLE
LoggersNamedForEnclosingClass should rewrite

### ISSUE THREAD

**Issue by koppor** [openrewrite/rewrite-logging-frameworks#105]
I think, the recipe says that a logger should use the `.class` by the class it is placed to.

I have the following Java-Code:

```java
public class PdfIndexer {

    private static final Logger LOGGER = LoggerFactory.getLogger(LibraryTab.class);
```

(source: https://github.com/JabRef/jabref/blob/5343c7c5dadd1482ef8f01057364e8e4d1a1156e/src/main/java/org/jabref/logic/pdf/search/indexing/PdfIndexer.java#L44 - full code with activated rewrite at https://github.com/JabRef/jabref/pull/9886).

That rule does not trigger anything.

**Comment by timtebeek** [comment]
That's odd indeed; it ought to trigger and I see no reason why it wouldn't. 🤔

**Comment by koppor** [comment]
Maybe, some gradle issues?

**Comment by timtebeek** [comment]
I don't know; same result locally, also if I remove some of the Gradle file exclusions you added.
Will wait for 8.0 release and then try again through the platform to rule out Gradle plugin issues.

**Comment by koppor** [comment]
I'll join the waiting queue 😅. Keeping thumbs pushed for the release!

**Comment by koppor** [comment]
Similar issue for ParameterizedLogging - I think, following code should be rewritten:

```java
LOGGER.info("Executing command \"{}" + command + "\"...");
```

**Comment by timtebeek** [comment]
> Similar issue for ParameterizedLogging - I think, following code should be rewritten:
> 
> ```java
> LOGGER.info("Executing command \"{}" + command + "\"...");
> ```

That's a bit of an odd case though right? since the logging statement already contains `{}` without any arguments? We'd then have to escape the first `{}` to stay true to the original code. Not sure if we have explicit exclusions, but you're welcome to look through our [existing test cases](https://github.com/openrewrite/rewrite-logging-frameworks/blob/main/src/test/java/org/openrewrite/java/logging/ParameterizedLoggingTest.java) for what should and should not already be covered.
