### ISSUE TITLE
Consider Lombok annotations for loggers

### ISSUE THREAD

**Issue by miguelchico** [openrewrite/rewrite-logging-frameworks#114]
## What problem are you trying to solve?
I'm trying to use logging recipes in a project that uses Lombok to declare SLF4J loggers.
The recipes I've tried so far don't change my source code if the logger instance is created by the Lombok Slf4j annotation.

For example try to use the "Use logger instead of printStackTrace()" with the following code:

```java
package justatest;

import org.slf4j.Logger;

@Slf4j
public class Test {

  void thisIsJustATest() {
      try {
      } catch (Exception e) {
        e.printStackTrace()
      }
  }

}
```

and it won't make any changes to the code.

If I don't use the Lombok annotation and just create a Logger by myself, everything works perfectly

## Describe the solution you'd like

It is desirable that Lombok annotations are included in the existing recipes (not just the one in the example above)

## Have you considered any alternatives or workarounds?

There is no workaround possible that I'm aware of

**Comment by timtebeek** [comment]
Hi @migualchico; interesting case! In part this is down to OpenRewrite not yet supporting Lombok annotations; support for that is tracked in:
- https://github.com/openrewrite/rewrite/issues/1297

Because we don't yet support Lombok annotations, this conditional fails, as there's no such field found
https://github.com/openrewrite/rewrite-logging-frameworks/blob/73eb21a1ae9475196c78d5ea7817ce7651f55093/src/main/java/org/openrewrite/java/logging/PrintStackTraceToLogError.java#L79-L80

We can likely do two things to hope to resolve your immediate issue:
1. generically support the lombok logging annotations by adding a synthetic logging field, that's available to recipes, but not modifiable or printed (high effort and complexity)
2. specifically for this recipe, look for lombok logging annotations, and if found, generate a logging template that uses the default "log" field generated (for simplicity, not taking into account [lombok.log.fieldName](https://projectlombok.org/features/log))

The second approach might be easier to tackle, starting with a draft pull request that merely adds a test to verify the desired behavior. Would you be willing to try your hand at that?

**Comment by timtebeek** [comment]
Thanks for reporting your findings here! This should be fixed in
- #115 

You can try out this change through [our snapshot versions](https://docs.openrewrite.org/reference/snapshot-instructions), pending the next release.
