### ISSUE TITLE
Replace e.printStackTrace() with a proper logging statement.

### ISSUE THREAD

**Issue by rdifrango** [openrewrite/rewrite-logging-frameworks#45]
I was fixing an application that had a ton of `e.printStackTrace()` and when I run the logging conversion tools, I would like those to be removed in favor of a proper logging statement perhaps something like:

```
logger.error("Error", e);
```

**Comment by pway99** [comment]
Hi @rdifrango,  Going to close this issue since a recipe already exists for this case; it's in the `org.java.logging` package. I overlooked it also.

https://github.com/openrewrite/rewrite-logging-frameworks/blob/49da20164b953a16297a61195a20db5c67b3f3b9/src/main/java/org/openrewrite/java/logging/PrintStackTraceToLogError.java#L31-L40
